----CREATE DATABASE SALE
----USE SALE
----GO
------DROP DATABASE SALE
---- KHACHANG
----DROP TABLE EMPLOYEE
----DROP TABLE CUSTOMER
CREATE TABLE COMPANYINFO(
COMPANYNAME nvarchar(300) PRIMARY KEY,
COMPANYADDRESS nvarchar(400),
COMPANYPHONE varchar(20),
CONCURENCY nvarchar(10),

)
CREATE TABLE CUSTOMER(
	CUSTID	int identity(1,1) PRIMARY KEY not null,	
	CUSTNAME	nvarchar(40) NOT NULL,
	CUSTADDRESS	nvarchar(50),
	CUSTPHONE	varchar(20),
	CUSTDOB	date, -- ngày sinh
	CUSTREGDATE	date, -- ngày đăng ký
)
INSERT INTO CUSTOMER VALUES('NGUYEN HUNG DUNG','87 MINH KHAI TP VINH','+8573648373','10/20/1999','10/10/2018')
INSERT INTO CUSTOMER VALUES('NGUYEN VAN DUNG','87 MINH KHAI TP VINH','+8573648373','10/20/1999','10/10/2018')
INSERT INTO CUSTOMER VALUES('LE DUC HUY','87 MINH KHAI TP VINH','+8573648373','10/20/1999','10/10/2018')
INSERT INTO CUSTOMER VALUES('HA DUC CHINH','87 MINH KHAI TP VINH','+8573648373','10/20/1999','10/10/2018')
INSERT INTO CUSTOMER VALUES('DANG VAN LAM','87 MINH KHAI TP VINH','+8573648373','10/20/1999','10/10/2018')
-----------------------------------------------
-- NHANVIEN
CREATE TABLE EMPLOYEE(
    --EMPID	int identity(1,1) PRIMARY KEY not null,	
	USERNAME varchar(10) not null primary key,
	PASS varchar(30) not null,
	ISADMIN int, -- 1 là admin, 0 hoặc null là employee
	EMPNAME	nvarchar(40) NOT NULL,
	EMPPHONE	nvarchar(20),
	EMPSTARTDATE	date	
)
INSERT INTO EMPLOYEE VALUES('admin','aptech123',1,'admin name2','+84368273672','12/12/2018')
INSERT INTO EMPLOYEE VALUES('kiendt','aptech123',0,'Dinh Trung Kien','+84368273672','12/12/2018')
INSERT INTO EMPLOYEE VALUES('hungdt','aptech123',0,'Duong Thanh Hung','+8436845653','12/12/2018')
INSERT INTO EMPLOYEE VALUES('datdq','aptech123',0,'Dat Quoc Dang','+84368245672','12/12/2018')
INSERT INTO EMPLOYEE VALUES('tanbh','aptech123',0,'Tan Bui Huu','+843682745544','12/12/2018')
INSERT INTO EMPLOYEE VALUES('xayasin','aptech123',0,'Phonnasane Xayasin','+84458273442','12/12/2018')
-------CATEGORY-----------
CREATE TABLE CATEGORY(
CATEGORYID int identity(1,1) primary key,
CATEGORYNAME nvarchar(4000),
)
------
INSERT INTO CATEGORY VALUES('SMART PHONE')
INSERT INTO CATEGORY  VALUES('LAPTOP')
INSERT INTO CATEGORY  VALUES('ACCESSORIES')
-----------------------------------------------
-- SANPHAM
CREATE TABLE PRODUCT(
	PRODUCTID int identity(1,1) PRIMARY KEY not null,
	PRODUCTNAME	nvarchar(40),
	UNIT	nvarchar(20),
	AMOUNT int, -- tồn kho
	COMPANY	varchar(40),
	PRICE	money,
	PRODUCTCODE varchar(30),
	[CATEGORYID] int foreign key references CATEGORY(CATEGORYID),
	DETAILS ntext,
)
---
--ALTER TABLE PRODUCT ADD  DETAILS ntext
--ALTER TABLE PRODUCT ALTER column PRICE float
INSERT INTO PRODUCT VALUES('GALAXY S10','PIECES',200,'SAMSUNG INC',1000,'SMART01',1,'ĐIỆN THOẠI SAMSUNG GALAXY S10')
INSERT INTO PRODUCT VALUES('GALAXY S9','PIECES',200,'SAMSUNG INC',1000,'SMART02',1,'ĐIỆN THOẠI SAMSUNG GALAXY S9')
INSERT INTO PRODUCT VALUES('GALAXY S8','PIECES',200,'SAMSUNG INC',1000,'SMART03',1,'ĐIỆN THOẠI SAMSUNG GALAXY S8')
INSERT INTO PRODUCT VALUES('IPHONE XS MAX','PIECES',200,'APPLE INC',1000,'SMART04',1,'ĐIỆN THOẠI APPLE IPHONE XS MAX')
INSERT INTO PRODUCT VALUES('IPHONE 7 PLUS','PIECES',200,'APPLE INC',1000,'SMART05',1,'ĐIỆN THOẠI APPLE IPHONE 7 PLUS')
-------------------------------------------
 ----HOADON
------------------CREATE TABLE BILL(
------------------	BILLID	int identity(1,1) PRIMARY KEY not null,
------------------	BILLDATE 	date,
------------------	CUSTID INT,
------------------	USERNAME 	varchar(10) foreign key  references EMPLOYEE(USERNAME),
------------------	PRODUCT ntext,-- LIÊN KẾT TỚI INTERFACE PRODUCT TRONG ĐÓ, XÀI ARRAYLIST tostring.
------------------	-- BAO GOM ID, SO LUONG, GIA TIEN,...
------------------	----AMOUNT	money,
------------------)
---------------------- productid+"|"+productname+"|"+unit+"|"+amount+"|"+price
------------------INSERT INTO BILL VALUES('10/12/2018',2,'kiendt','1|GALAXY S10|PIECES|1|1000')
------------------INSERT INTO BILL VALUES('11/12/2018',2,'admin','2|GALAXY S9|PIECES|1|1000')
------------------INSERT INTO BILL VALUES('12/12/2018',2,'admin','1|GALAXY S10|PIECES|1|1000,4|IPHONE XS MAX|PIECES|1|1000')
--INSERT INTO BILL VALUES('09/12/2018',2,'admin','1|GALAXY S10|PIECES|1|1000')
CREATE TABLE BILL(
	BILLID	int identity(1,1) PRIMARY KEY not null,
	BILLDATE 	date,
	CUSTID INT,
	USERNAME 	varchar(10) foreign key  references EMPLOYEE(USERNAME),
	----BILLDETAILID INT foreign key references BILLDETAIL(BILLDETAILID),
	)
CREATE TABLE BILLDETAIL(
BILLID INT  foreign key references BILL(BILLID),
PRODUCTID int foreign key references PRODUCT(PRODUCTID),
AMOUNT INT,
constraint pk_billdetail primary key(BILLID,PRODUCTID)

)

ALTER TABLE BILL ADD CONSTRAINT BILLFK FOREIGN KEY(CUSTID) REFERENCES CUSTOMER(CUSTID)
INSERT INTO COMPANYINFO VALUES('ABC MOBILE', '87 MINH KHAI ST, VINH, NGHE AN ','+84736736383','USD')
---- 
--DEMO DATA
INSERT INTO BILL VALUES ('12/12/2018',1,'admin')

INSERT INTO BILLDETAIL VALUES(1,3,1)
INSERT INTO BILLDETAIL VALUES(1,1,1)
-----------
INSERT INTO BILL VALUES ('12/20/2018',2,'kiendt')
INSERT INTO BILLDETAIL VALUES(2,1,2)
INSERT INTO BILLDETAIL VALUES(2,2,1)
