/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainForm;

import Entity.Bill;
import Entity.Employee;
import Entity.Product;
import java.awt.Color;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import javax.persistence.EntityManager;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author KIENDINH
 */
public class OrderFrm extends javax.swing.JFrame {

    private final static String unitName = "SaleManagerProjectPU";
    private static final EntityManager entityManager = Persistence.createEntityManagerFactory(unitName).createEntityManager();

    /**
     * Creates new form Order
     */
    public OrderFrm() {
        initComponents();
        setLocationRelativeTo(null);
        //this.tblOrder.setGridColor(Color.GRAY);
        //setData();
    }

    private void setData() {
        try {
            tblOrder.setModel(new DefaultTableModel());
            //EntityManager entityManager = Persistence.createEntityManagerFactory(unitName).createEntityManager();
            Query query = entityManager.createNamedQuery("Bill.findAll");
            List<Bill> resultList = query.getResultList();

            Vector<String> tableHeaders = new Vector<>();
            Vector tableData = new Vector();

            tableHeaders.add("BILL ID");
            tableHeaders.add("BILL DATE");
            tableHeaders.add("EMPLOYEE");
            //tableHeaders.add("PRODUCT");

            for (Bill e : resultList) {
                Vector<Object> oneRow = new Vector<Object>();
                oneRow.add(e.getBillid());
                oneRow.add(e.getBilldate());
                oneRow.add(e.getUsername());
                //oneRow.add(e.getProduct());
                tableData.add(oneRow);
            }
            DefaultTableModel aModel = new DefaultTableModel(tableData, tableHeaders) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }

            };
            this.tblOrder.setModel(aModel);

            //       tblOrder.setEnabled(false);
//        JTableHeader header = tblOrder.getTableHeader();
//         tblEmployee.getTableHeader().setOpaque(false);
//         header.setBackground(Color.WHITE);
//         header.setForeground(Color.BLACK);
        } catch (Exception he) {
            he.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        SaleManagerProjectPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("SaleManagerProjectPU").createEntityManager();
        billQuery = java.beans.Beans.isDesignTime() ? null : SaleManagerProjectPUEntityManager.createQuery("SELECT b FROM Bill b");
        billList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : billQuery.getResultList();
        jPanel1 = new javax.swing.JPanel();
        jScrollOrder = new javax.swing.JScrollPane();
        tblOrder = new javax.swing.JTable() {
            public boolean isCellEditable(int row, int column) {
                return false;
            };
        };
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProduct = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblCust = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCost = new javax.swing.JLabel("",SwingConstants.RIGHT);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jScrollOrder.setBackground(new java.awt.Color(255, 255, 255));
        //jScrollOrder.getViewport().setBackground(Color.white);
        //jScrollOrder.setBorder(javax.swing.BorderFactory.createLineBorder(Color.DARK_GRAY));
        jScrollOrder.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        tblOrder.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tblOrder.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblOrder.setGridColor(new java.awt.Color(255, 255, 255));
        tblOrder.setRowHeight(30);
        tblOrder.setRowMargin(5);
        tblOrder.setShowHorizontalLines(false);
        tblOrder.setShowVerticalLines(false);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, billList, tblOrder);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${billdate}"));
        columnBinding.setColumnName("Billdate");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${billid}"));
        columnBinding.setColumnName("Billid");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${custid}"));
        columnBinding.setColumnName("Custid");
        columnBinding.setColumnClass(Entity.Customer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${username}"));
        columnBinding.setColumnName("Username");
        columnBinding.setColumnClass(Entity.Employee.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        tblOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblOrderMouseClicked(evt);
            }
        });
        jScrollOrder.setViewportView(tblOrder);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Old Order List:");

        tblProduct.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane2.setViewportView(tblProduct);

        jButton1.setLabel("Delete Order");

        jButton2.setLabel("New Order");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setLabel("Print Order");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        tblCust.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane3.setViewportView(tblCust);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Customer Infomation:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Product in order:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel4.setText("Total Cost:");

        txtCost.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtCost.setText("0.0000");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(335, 335, 335))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCost, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCost, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollOrder))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblOrderMouseClicked
        int r = this.tblOrder.getSelectedRow();
        TableModel model = tblOrder.getModel();
        if (r != -1) {
            String billid = (model.getValueAt(r, 1) != null ? model.getValueAt(r, 1).toString() : "");
            String custid = (model.getValueAt(r, 2) != null ? model.getValueAt(r, 2).toString() : "");
            this.tblProduct.setModel(new DefaultTableModel());
            setProductTable(billid);
            setCustomerTable(custid);
        }

    }//GEN-LAST:event_tblOrderMouseClicked
    private void setProductTable(String billid) {
        List<Product> resultList1 = new ArrayList<Product>();
        try {
            String sql = "SELECT b.PRODUCTID, b.PRODUCTNAME,b.PRODUCTCODE,b.PRICE,b.UNIT, a.AMOUNT FROM BILLDETAIL a "
                    + "INNER JOIN PRODUCT b ON a.PRODUCTID = b.PRODUCTID" +
                            " WHERE a.BILLID = '"+billid+"'";
            // String sql2 = "SELECT * FROM Customer where custid = '" + custid + "' ";
//            Query query = entityManager.createNativeQuery(sql, Product.class);
//            resultList1 = query.getResultList();
//            entityManager.clear();
            Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost;databaseName=SALE", "sa","123456");
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            //resultList1 = rs
            Vector<String> tableHeaders;
            tableHeaders = new Vector<>();
            Vector tableData = new Vector();
             tableHeaders.add("PRODUCT ID");
            tableHeaders.add("PRODUCT NAME");
            tableHeaders.add("PRODUCT CODE");
            tableHeaders.add("UNIT");
            tableHeaders.add("AMOUNT");
            tableHeaders.add("TOTAL PRICE");
            float cost = 0;
            while(rs.next())
            {
                Vector<Object> oneRow = new Vector<Object>();
                float amt = rs.getFloat("AMOUNT");
                oneRow.add(rs.getInt(1));
                oneRow.add(rs.getString(2));
                oneRow.add(rs.getString(3));
                oneRow.add(rs.getInt(4));
                oneRow.add(amt);
                float price = amt * rs.getFloat("PRICE");
                oneRow.add(price);
                tableData.add(oneRow);
                cost += price;
            }
//            for (Product e : resultList1) {
//                //JOptionPane.showMessageDialog(null, e.getProductname());
//                Vector<Object> oneRow = new Vector<Object>();
//                float amt = e.getAmount();
//                oneRow.add(e.getProductname());
//                oneRow.add(e.getProductcode());
//                oneRow.add(e.getUnit());
//                oneRow.add(amt);
//                float price = amt * e.getPrice();
//                oneRow.add(price);
//                tableData.add(oneRow);
//                cost += price;
//            }
            txtCost.setText("" + cost);
            DefaultTableModel aModel = new DefaultTableModel(tableData, tableHeaders) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }

            };
            
            this.tblProduct.setModel(aModel);
            tblProduct.setAutoResizeMode(WIDTH);
        } catch (Exception he) {
            he.printStackTrace();
        }

    }

    private void setCustomerTable(String custid) {

        try {

            //String sql2 = "SELECT * FROM Customer where custid = '" + custid + "' ";
            Query query = entityManager.createNamedQuery("Customer.findByCustid");
            query.setParameter("custid", Integer.parseInt(custid));
            Entity.Customer c = (Entity.Customer) query.getSingleResult();
            entityManager.clear();
            Vector<String> row = new Vector<>();
            Vector<Object> content = new Vector<Object>();
            Vector tbHeader = new Vector();
            tbHeader.add("Customer Name");
            tbHeader.add("Customer Address");
            tbHeader.add("Customer Phone");
            row.add(c.getCustname());
            row.add(c.getCustaddress());
            row.add(c.getCustphone());
            content.add(row);
            DefaultTableModel custModel = new DefaultTableModel(content, tbHeader) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }

            };
            this.tblCust.setModel(custModel);
            tblCust.setAutoResizeMode(WIDTH);

        } catch (Exception he) {
            he.printStackTrace();
        }

    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
//        Product p1 = new Product();
//        p1.setProductid(1);
//        p1.setProductname("GALAXY S7");
//        p1.setUnit("piece");
//        p1.setAmount(1);
//        p1.setPrice(BigDecimal.valueOf(900));
//        Product p2 = new Product();
//        p2.setProductid(1);
//        p2.setProductname("IPHONE XS MAX");
//        p2.setUnit("piece");
//        p2.setAmount(1);
//        p2.setPrice(BigDecimal.valueOf(920));
//        JOptionPane.showMessageDialog(null,p1+"/r/n"+p2);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        newBill n = new newBill();
        this.setVisible(false);
        n.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderFrm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderFrm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderFrm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderFrm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderFrm().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager SaleManagerProjectPUEntityManager;
    private java.util.List<Entity.Bill> billList;
    private javax.persistence.Query billQuery;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollOrder;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblCust;
    private javax.swing.JTable tblOrder;
    private javax.swing.JTable tblProduct;
    private javax.swing.JLabel txtCost;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
